-- MySQL Script generated by MySQL Workbench
-- Mon Aug 15 17:11:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema onlineshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema onlineshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onlineshop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `onlineshop` ;

-- -----------------------------------------------------
-- Table `onlineshop`.`settings_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`settings_group` (
  `groupid` BIGINT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`groupid`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `onlineshop`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`settings` (
  `settingid` BIGINT NOT NULL AUTO_INCREMENT,
  `ordinal` INT NULL DEFAULT NULL,
  `setting_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `status` BIT(1) NULL DEFAULT NULL,
  `groupby` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`settingid`),
  INDEX `FKqv9cu8dv6upwogfg87qmac11u` (`groupby` ASC) VISIBLE,
  CONSTRAINT `FKqv9cu8dv6upwogfg87qmac11u`
    FOREIGN KEY (`groupby`)
    REFERENCES `onlineshop`.`settings_group` (`groupid`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `onlineshop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`products` (
  `productid` BIGINT NOT NULL AUTO_INCREMENT,
  `discount` INT NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `summary` VARCHAR(300) NULL DEFAULT NULL,
  `thumbnail` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(50) NULL DEFAULT NULL,
  `category` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`productid`),
  INDEX `FKkuob0jahtq5ewe4yi6rklh0vd` (`category` ASC) VISIBLE,
  CONSTRAINT `FKkuob0jahtq5ewe4yi6rklh0vd`
    FOREIGN KEY (`category`)
    REFERENCES `onlineshop`.`settings` (`settingid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `onlineshop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlineshop`.`users` (
  `userid` BIGINT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `avartar` VARCHAR(255) NULL DEFAULT NULL,
  `dob` DATETIME(6) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `gender` BIT(1) NULL DEFAULT NULL,
  `fullname` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(11) NULL DEFAULT NULL,
  `role` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`userid`),
  INDEX `FKdwpauhakcmrfdparg89bp11ly` (`role` ASC) VISIBLE,
  CONSTRAINT `FKdwpauhakcmrfdparg89bp11ly`
    FOREIGN KEY (`role`)
    REFERENCES `onlineshop`.`settings` (`settingid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
