logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carpark_project?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: Nxduc1506@

server:
  port: 8080
